### ISSUE TITLE
Document how locust-service could be used in parallel to the default jmeter-service

### ISSUE THREAD

**Issue by tolleiv** [keptn-sandbox/locust-service#50]
Hi,
compared to the default jmeter-service this service acts differently when no configuration is present - it will fail rather than "skipping". That's a problem when running jmeter-service for some project services and locust-service for others.

In case the configuration is missing, the service should successfully "skip" it's execution - that's what the jmeter-server does and that also seems to be the concept -> https://keptn.slack.com/archives/CNRCGFU3U/p1624375402161500.

**Comment by jetzlstorfer** [comment]
Hi @tolleiv thanks for this suggestion. 
As a workaround you can change the distributor to only subscribe to projects or services where you want the Locust service to run. You can find more information here: https://keptn.sh/docs/0.8.x/integrations/custom_integration/#subscription-to-a-triggered-event 

However, you are right. If no test file is configured, the Locust integration should just skip the task.

**Comment by TannerGilbert** [comment]
@tolleiv @jetzlstorfer I'll look into changing the locust-service so it behaves the same as the jmeter-service.

**Comment by jetzlstorfer** [comment]
cool! thanks @TannerGilbert
